name: gthqrscanner
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.2
  barcode_scan2: ^4.2.0
  gsheets: ^0.3.2
  firebase_core: ^1.12.0
  cloud_firestore: ^3.1.8
  flutter_switch: ^0.3.2
  awesome_dialog: ^2.1.2
  animated_text_kit: ^4.2.1
  url_launcher: ^6.0.20
  webview_flutter: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/img/
